(function(){for(var a=0,c=["ms","moz","webkit","o"],b=0;b<c.length&&!window.requestAnimationFrame;++b)window.requestAnimationFrame=window[c[b]+"RequestAnimationFrame"],window.cancelAnimationFrame=window[c[b]+"CancelAnimationFrame"]||window[c[b]+"CancelRequestAnimationFrame"];window.requestAnimationFrame||(window.requestAnimationFrame=function(c){var b=(new Date).getTime(),f=Math.max(0,16-(b-a)),h=window.setTimeout(function(){c(b+f)},f);a=b+f;return h});window.cancelAnimationFrame||(window.cancelAnimationFrame=
function(a){clearTimeout(a)})})();
(function(){function a(a,c){a?"function"!=typeof a?console.warn("rafScroll: Invalid callback type."):(this._scrolling=!1,this._callback=a,this._args=c||[],this.subscribe()):console.warn("rafScroll: No callback supplied, not initiating.")}function c(a){this._mostRecentScrollEvent=a;!1===this._scrolling&&(this._scrolling=!0,b.call(this));this._scrollTimeout&&clearTimeout(this._scrollTimeout);var c=this;this._scrollTimeout=setTimeout(function(){c._scrolling=!1},100)}function b(){this._args.unshift(this._mostRecentScrollEvent);
this._callback.apply(window||{},this._args);this._args.shift();!0===this._scrolling&&requestAnimationFrame(b.bind(this))}window.requestAnimationFrame?(a.prototype={subscribe:function(){addEventListener("scroll",c.bind(this),!1)},unsubscribe:function(){removeEventListener("scroll",c.bind(this),!1)}},"function"===typeof define&&define.amd?define("rafscroll",a):"undefined"!==typeof module&&"undefined"!==typeof exports?module.exports={rafscroll:a}:window.rafscroll=a):console.info("Your browser does not support requestAnimationFrame. There is a nice polyfill you can use here.",
"https://gist.github.com/paulirish/1579671")})();
(function(){var a=function(a){var b=window.MutationObserver||window.WebKitMutationObserver||window.MozMutationObserver;b&&(this.targets=a.targets||[document.body.querySelector(".sqs-block-form"),document.body.querySelector(".sqs-block-tourdates"),document.body.querySelector(".sqs-block-code")],this.options={childList:!0,subtree:!0},this.callback=a.callback,this.args=a.args||{},this.observer=this.createObserver(b),this.observeTargets())};a.prototype={createObserver:function(a){var b=this;return new a(function(a){b.evaluateMutations(a,
b)})},observeTargets:function(){for(var a=this.targets.length,b=0;b<a;b++){var e=this.targets[b];e&&this.observer.observe(e,this.options)}},bind:function(){window.addEventListener("beforeunload",function(){this.destruct()})},destruct:function(){this.observer.disconnect();this.observer=null},evaluateMutations:function(a,b){if(a)for(var e=0;e<a.length;e++)if("childList"===a[e].type){"complete"===document.readyState?b.reactToMutations():document.addEventListener("DOMContentLoaded",function(){b.reactToMutations()},
!1);break}},reactToMutations:function(){this.timer&&clearTimeout(this._timer);var a=this;this.timer=setTimeout(function(){a.callback.apply(window||{},this.args)},150)}};window.templateMutationObserver=a})();var DEBUG=!0;
Y.use(["node","squarespace-ui-base","yui-throttle","squarespace-gallery-ng"],function(a){window.Site=Singleton.create({PARALLAX_FACTOR:0.8,SCROLL_SPEED:0.6,IMAGE_VIEWPORT:null,INITIAL_WINDOW_HEIGHT:a.config.win.innerHeight,pageOffsets:{},docHeight:0,ready:function(){DEBUG&&(this._readyTime=Date.now());document.addEventListener("DOMContentLoaded",this.guardedInitialize.bind(this));a.on("domready",this.guardedInitialize,this)},guardedInitialize:function(){!0===this._guardedInitializeAlreadyRan?(DEBUG&&
console.log("guarding invocation of initialize!"),this.syncUI(),this.positionImages()):(DEBUG&&console.log(Date.now()-this._readyTime+"ms between ready and initialize."),this._guardedInitializeAlreadyRan=!0,this.initialize())},initialize:function(){this.parallaxImages=a.all("#parallax-images .image-container");this.parallaxPages=a.all(".parallax-item");this.scrollEl=a.one(a.UA.gecko||a.UA.ie||navigator.userAgent.match(/Trident.*rv.11\./)?"html":"body");this.viewportH=a.one("body").get("winHeight");
this.isMobile=!a.Lang.isUndefined(window.orientation)||0<a.UA.ie&&9>=a.UA.ie;this.bindUI();this.syncUI();this.textShrink(".page-title",".page-title-wrapper");this.textShrink(".page-desc p \x3e strong",".page-desc p");this.textShrink(".collection-type-events.view-list .entry-title-wrapper h1.entry-title",".collection-type-events.view-list .entry-title-wrapper");this.textShrink(".collection-type-blog.view-list.blog-layout-columns .entry-title-wrapper h1.entry-title",".collection-type-blog.view-list.blog-layout-columns .entry-title-wrapper");
a.one("body.collection-type-index")&&this.handleIndex();this.listenTweaks();a.one("body").addClass("loaded");a.UA.ie&&a.one("html").addClass("ie"+a.UA.ie);this.isMobile||a.one("html").removeClass("touch");if(!a.one(".sqs-edit-mode-active")&&(a.one(".sqs-block-gallery")||a.one(".sqs-block-summary-v2"))){var c=this,b=setInterval(function(){a.one("img.loading")||(c.syncUI(),a.one("body.collection-type-index")&&c.handleIndex(),clearInterval(b))},100);setTimeout(function(){clearInterval(b)},6E4)}},handleIndex:function(){if(a.config.win.location.hash)this.onHashChange({newHash:window.location.hash.replace("#",
""),quick:!0});else this.updateActivePage();this.positionImages()},bindUI:function(){if(a.one("body.collection-type-index")){var c=a.one(".scroll-arrow");if(c)c.on("click",function(){var b=c.ancestor(".title-desc-wrapper").next(".content");if(b){var d=new a.Anim({node:a.one(a.UA.gecko||a.UA.ie||navigator.userAgent.match(/Trident.*rv.11\./)?"html":"body"),to:{scrollTop:b.getY()},duration:0.5,easing:"easeOut"});d.run();d.on("end",function(){d.destroy()})}});new rafscroll(a.bind(function(){this.positionImages();
a.one("#parallax-nav")&&this.updateActivePage()},this));var b=a.UA.mobile?"orientationchange":"resize";a.one(a.config.win).on("resize",a.throttle(a.bind(function(){this.syncUI();this.positionImages()},this),50),this);a.on("hashchange",a.bind(this.onHashChange,this),a.config.win);a.all("#parallax-nav a").each(function(a){a.on("click",function(){if(a.getAttribute("href")===window.location.hash)this.onHashChange({newHash:a.getAttribute("href").replace("#","")})},this)},this);a.one(".back-to-top-link a").on("click",
function(b){b.halt();this.onHashChange({newHash:a.one("[data-url-id]").getAttribute("data-url-id")})},this);a.all('#desktopNav .external-link a[href*\x3d"#"]').each(function(b){b.on("click",function(c){var f=a.one(b.getAttribute("href"));if(f){var h=f.getXY()[1];c.preventDefault();this.autoScrolling=!0;this.scrollEl.anim({},{to:{scroll:[0,h]},duration:this.SCROLL_SPEED,easing:a.Easing.easeBoth}).run().on("end",function(){this.scrollEl.get("scrollTop")!==h&&this.scrollEl.set("scrollTop",h);this.autoScrolling=
!1;this.updateActivePage()},this)}},this)},this);new templateMutationObserver({callback:a.bind(function(){this.syncUI();this.positionImages()},this)})}else a.one(a.config.win).on("scroll",a.bind(function(){this.positionBackgroundImage()},this),this),b=a.UA.mobile?"orientationchange":"resize",a.one(a.config.win).on(b,a.throttle(a.bind(function(){this.syncUI();this.positionBackgroundImage()},this),50),this);this.setupMobileNav();this.setScrollArrowColor()},syncUI:function(){var c=a.one("body"),b=a.one("#header").get("clientHeight"),
e=c.hasClass("fixed-header"),d=c.hasClass("title--description-position-over-image");this.parallaxOff="false"==a.Squarespace.Template.getTweakValue("parallax-scrolling");this.viewportH=c.get("winHeight");this.docHeight=c.get("docHeight");if(a.one("body.collection-type-index")){this.isMobile?(this.setupMobileLayout(),a.one("#header").setStyle("position","absolute"),a.one(".sqs-cart-dropzone").setStyle("marginTop",b),a.one(".parallax-images \x3e .image-container:nth-child(1) \x3e img")&&a.one(".title-desc-wrapper").setStyle("minHeight",
"600px"),0<a.UA.ie&&9>=a.UA.ie?a.one(".title-desc-wrapper").setStyle("paddingTop",d?80+b:b):a.one(".title-desc-wrapper").setStyle("paddingTop",b)):(a.one("#content-wrapper").setStyle("marginTop",e?b:null),a.all(".title-desc-wrapper.has-main-image").setStyle("paddingTop",e&&d?80+b:null),a.one(".title-desc-wrapper.has-main-image")&&a.one(".title-desc-wrapper.has-main-image").setStyle("paddingTop",null));var f=a.Squarespace.Template.getTweakValue("index-image-height");this.IMAGE_VIEWPORT="Fullscreen"==
f?1:"Half"==f?0.5:0.66;this.firstImageHeight="true"===a.Squarespace.Template.getTweakValue("first-index-image-fullscreen")?this.viewportH:parseInt(this.viewportH*this.IMAGE_VIEWPORT);this.restImageHeight=parseInt(this.viewportH*this.IMAGE_VIEWPORT);var h=new a.NodeList;this.parallaxPages.each(function(c,f){if(!this.isMobile){var g=0===f?this.firstImageHeight-a.one("#header").get("clientHeight"):this.restImageHeight;if(d){var j=e?b+160:160,g=Math.max(g,c.one(".title-desc-inner").height()+j),j=0===
f?g+b:g;this.parallaxImages.item(f).setStyle("height",Math.max(this.viewportH,j)+"px")}if(j=this.parallaxImages.item(f).one("img"))c.one(".title-desc-wrapper").setStyle("height",g+"px"),h.push(j.removeAttribute("data-load"))}this.pageOffsets[c.getAttribute("data-url-id")]=0===f?0:Math.round(c.getXY()[1])},this);a.Squarespace.GalleryManager.addImageQueue(h);this.parallaxImages.each(function(a){(a=a.one("img"))&&a.getAttribute("src")&&ImageLoader.load(a)},this);this.stickyCart()}else(f=a.one(".banner-image img"))&&
ImageLoader.load(f),a.one(".sqs-cart-dropzone").setStyle("marginTop",b),this.stickyCart(),this.isMobile||a.one("#header-wrapper").setStyle("paddingTop",e?b:null);this.isMobile||(a.one(".collection-type-index.title--description-alignment-center.title--description-position-over-image")&&a.all(".title-desc-wrapper.has-main-image").each(function(a){a.one(".title-desc-inner").setStyles({top:"50%",left:"50%",transform:"translatex(-50%) translatey(-50%)"})}),a.one(".collection-type-index.title--description-alignment-left")&&
a.all(".title-desc-wrapper.over-image.has-main-image .title-desc-inner").setStyles({top:null,left:null,transform:"translatex(0) translatey(0)"}),a.one("#parallax-nav")&&(f=a.one("#parallax-nav").get("offsetHeight"),a.one("#parallax-nav").setStyle("marginTop",-1*(f/2))));a.one(".footer-wrapper .sqs-block")||a.one(".footer-wrapper").addClass("empty");a.one(".nav-wrapper")&&c.addClass("has-nav");this.headerBgOnScroll()},textShrink:function(c,b){a.one(c)&&a.one(c).ancestor(b)&&a.all(c).each(function(c){c.plug(a.Squarespace.TextShrink,
{parentEl:c.ancestor(b)})})},setupMobileLayout:function(){var c=a.config.win.innerHeight>a.config.win.innerWidth?screen.height:screen.width,b=a.Squarespace.Template.getTweakValue("index-image-height"),e=a.one("#header").get("clientHeight"),d;switch(!0){case "Two Thirds"==b:d=0.66666*c;break;case "Fullscreen"==b:d=1*c;break;default:d=0.5*c}var f=a.one(a.config.doc.body).hasClass("mobile-styles-disabled");a.all(".parallax-item").each(function(b,c){var i=b.one(".title-desc-wrapper"),g=b.one(".title-desc-inner"),
j=b.one(".title-desc-image");if(i.hasClass("has-main-image")){var k;0===c&&!f?(d-=118,k=this.INITIAL_WINDOW_HEIGHT-e):k=d;var l=g.get("clientHeight");l>k&&(k=d=l);i.setStyles({height:k,overflow:"hidden"},this);j.setStyles({height:d})}else i.setStyle({paddingTop:e});a.one(".title--description-alignment-center")&&i.hasClass("has-main-image")&&(g.get("clientHeight")<i.get("clientHeight")&&0!==c?g.setStyles({position:"absolute",top:"50%",left:"50%",transform:"translate3d(-50%, -50%, 0)"}):g.setStyles({position:"relative"}),
0===c&&(b.one(".scroll-arrow").setStyles({marginTop:"-78px"}),g.get("clientHeight")+78<i.get("clientHeight")-a.one("#header").height()?g.setStyles({position:"absolute",top:"50%",left:"50%",transform:"translate3d(-50%, -50%, 0)"}):g.setStyles({position:"relative",marginBottom:"78px"})))},this);!a.one(".parallax-scrolling")||0<a.UA.ie&&9>=a.UA.ie?(0<a.UA.ie&&9>=a.UA.ie?a.one("body").addClass("crappy-ie-no-parallax"):a.one("body").addClass("mobile-no-parallax"),a.all(".title-desc-image").each(function(b,
c){0===c&&b.setStyles({minHeight:b.ancestor(".title-desc-wrapper").get("clientHeight")+a.one("#header").get("clientHeight")});b.one("img").removeAttribute("data-load");ImageLoader.load(b.one("img"),{mode:"fill"})})):(a.one("body").addClass("mobile-parallax"),a.all(".title-desc-image").each(function(a){a.setStyle("height",c);a.one("img").removeAttribute("data-load");ImageLoader.load(a.one("img"),{mode:"fill"})}))},setupMobileNav:function(){a.one("#mobileMenu").on("click",function(){a.one("body").hasClass("mobile-nav-open")?
a.one("body").removeClass("mobile-nav-open"):a.one("body").addClass("mobile-nav-open")});a.all("li.folder").each(function(a){a.on("click",function(){var b=a.siblings("li.folder.dropdown-open").item(0);b&&b.toggleClass("dropdown-open");a&&a.toggleClass("dropdown-open")})})},positionBackgroundImage:function(){var c=this.scrollEl.get("scrollTop"),b=a.one(a.config.win).get("region"),e=a.one(".banner-image img");!this.parallaxOff&&(!this.isMobile&&e&&!(c>b.height))&&e.setStyle("transform","translate3d(0,"+
parseInt(c*this.PARALLAX_FACTOR,10)+"px,0)")},onHashChange:function(c){a.one(".mobile-nav-open")&&a.one("body").removeClass("mobile-nav-open");if(a.one('.parallax-item[data-url-id\x3d"'+c.newHash+'"]')){var b=this.pageOffsets[c.newHash];c.quick?(this.scrollEl.set("scrollTop",b),this.updateActivePage()):(this.autoScrolling=!0,this.scrollEl.anim({},{to:{scroll:[0,b]},duration:this.SCROLL_SPEED,easing:a.Easing.easeBoth}).run().on("end",function(){this.scrollEl.get("scrollTop")!==b&&this.scrollEl.set("scrollTop",
b);this.autoScrolling=!1;this.updateActivePage()},this))}},getPageFromOffset:function(a){if(this.parallaxPages.item(0)){var b=this.parallaxPages.item(0).getAttribute("data-url-id"),e;for(e in this.pageOffsets)a>=this.pageOffsets[e]&&this.pageOffsets[e]>this.pageOffsets[b]&&(b=e);return b}},setScrollArrowColor:function(){var c=a.one(".scroll-arrow"),b=a.one(".parallax-item .title-desc-wrapper");b&&(b=b.getAttribute("data-color-suggested"),a.Lang.isValue(c)&&a.Lang.isValue(b)&&(b="color-weight-"+this._getLightness(b),
c.hasClass(b)||c.removeClass("color-weight-dark").removeClass("color-weight-light").addClass(b)))},updateActivePage:function(){if(!this.autoScrolling){var c=this.scrollEl.get("scrollTop"),b=this.getPageFromOffset(c),e=a.one("#parallax-nav-item-"+b);e&&!e.hasClass("active")&&(a.all("#parallax-nav li").removeClass("active"),e.addClass("active"));window.location.hash.replace("#","")!=b&&window.history&&window.history.replaceState&&window.history.replaceState({},"","#"+b);b=this.isMobile?a.one('.parallax-item[data-url-id\x3d"'+
b+'"] .title-desc-wrapper img'):a.one('#parallax-images .image-container[data-url-id\x3d"'+b+'"] img');a.Squarespace.GalleryManager.promoteImageQueue(new a.NodeList(b));if(!a.one("body.hide-parallax-nav")){var b=this.getPageFromOffset(c+this.viewportH/2),d;if(c+this.viewportH/2<=this.pageOffsets[b]+(0===this.pageOffsets[b]?this.firstImageHeight:this.viewportH*this.IMAGE_VIEWPORT))d=a.one('.parallax-item[data-url-id\x3d"'+b+'"] .title-desc-wrapper').getAttribute("data-color-suggested");if(!d||"#"===
d)d=a.Squarespace.Template.getTweakValue("contentBgColor"),(c=d.match(/rgba\((\d+),(\d+),(\d+),(\d+)/))&&(d=this._rgb2hex(c[1],c[2],c[3]));a.one("#parallax-nav")&&(d="color-weight-"+this._getLightness(d),a.one("#parallax-nav").hasClass(d)||a.one("#parallax-nav").removeClass("color-weight-dark").removeClass("color-weight-light").addClass(d))}}},_rgb2hex:function(a,b,e){a=[a,b,e];for(b=0;2>=b;++b)a[b]=parseInt(a[b],10).toString(16),1==a[b].length&&(a[b]="0"+a[b]);return"#"+a.join("")},_getLightness:function(a){return a&&
0<a.length&&7>=a.length?(a=a.replace("#",""),8388607.5<parseInt(a,16)?"light":"dark"):""},positionImages:function(){if(!this.isMobile){var c=this.scrollEl.get("scrollTop"),b=a.one(a.config.win).get("region");this.parallaxPages.each(function(a,d){var f=this.parallaxImages.item(d);if(a.inRegion(b)){var h=this.pageOffsets[a.getAttribute("data-url-id")]-c,m=-1*parseFloat(h*(this.parallaxOff?0:this.PARALLAX_FACTOR)),i=f.one("img");f.setStyles({transform:"translate3d(0, "+h+"px, 0)"});i&&i.setStyle("transform",
"translatey("+m+"px) translatez(0)")}else f.setStyle("transform","translate3d(0, -100%, 0)")},this)}},listenTweaks:function(){a.Global&&(a.Global.on("tweak:change",function(a){a.getName().match(/image|parallax|title--description-alignment|fixed-header/i)&&this.syncUI()},this),a.Global.on("tweak:change",function(c){"transparent-header"==c.getName()&&a.one(".fixed-header")&&a.one("#header").setStyle("backgroundColor",null)}),a.Global.on(["tweak:reset","tweak:close"],function(){a.later(500,this,this.syncUI)},
this))},headerBgOnScroll:function(){var c=a.one(".fixed-header.transparent-header"),b=a.one("#header"),e=b.get("clientHeight"),d=a.Squarespace.Template.getTweakValue("headerBgColor");if(c){a.one(window).on("scroll",function(){a.one(".transparent-header")&&a.later(500,this,f)});var f=function(){a.config.win.scrollY>e?a.one("#header").setStyle("backgroundColor",d):b.setStyle("backgroundColor","transparent")}}},stickyCart:function(){if(this.isMobile)return!1;var c=a.one(".sqs-cart-dropzone");a.one("#header").get("clientHeight");
var b;c&&c.one(".yui3-widget")&&(b=c.one(".yui3-widget").getY(),a.one(window).on("resize",function(){b=c.getY()}),a.one("body.fixed-header")?c.addClass("fixed-cart").setStyles({top:a.one("#header").get("clientHeight")+10}):new rafscroll(function(){c.toggleClass("fixed-cart",a.config.win.scrollY>=b)}))}})});